name: receive tokens send from figma

on:
  repository_dispatch:
   types: update-tokens
   
jobs:
  build:
    name: receive figma .json tokens file and save it in a tokens folder
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      
      - name: mkdir "tokens" directory
        run: 'mkdir -p tokens'
      
      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          # it uses the name from your settings that was send as then tokenFileName parameter
          name: 'design-tokens.tokens.json'
          # it uses the json string that was send as the tokens parameter
          json: ${{ github.event.client_payload.tokens }}
          # it uses the directory named "tokens" to store this json file (change this if you changed it above to use a different folder)
          dir: 'tokens'
